# Generated by Django 5.1.4 on 2025-04-20 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi mieć postać: '+999999999'. Dozwolone 9 do 15 cyfr.", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
